### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leftshift** [leftshift/colorfuck#4]
We should probably put this under a license. 
@anuejn, since there's a few lines of code in here you wrote, any thoughts? @vidister, what about you?

**Comment by anuejn** [comment]
Sorry for slow response.
I`d vote for AGPLv3 all the things but i dont really care in this specific case ;)

**Comment by leftshift** [comment]
Thanks, AGPLv3 sounds good to me :)

**Comment by unfokus** [comment]
ACK
